<a href="https://colab.research.google.com/github/peakodev/data_science/blob/feature%2Fhome1/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
!pip install numpy

In [27]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [28]:
natural_numbers = np.arange(1, 11)
vector = np.array(natural_numbers, dtype='u1')
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [29]:
matrix_zeros = np.zeros((3, 3), dtype='u1')
matrix_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [30]:
random_matrix_55 = np.random.randint(1, 11, size=(5, 5), dtype='u1')
random_matrix_55

array([[ 9,  6,  4,  2,  6],
       [ 8,  4,  2,  2,  4],
       [ 8,  7,  4,  9, 10],
       [ 3,  2,  4,  2,  8],
       [ 5,  2,  5,  4,  1]], dtype=uint8)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [31]:
matrix_b = np.random.rand(4, 4)
matrix_b

array([[0.65055621, 0.38618685, 0.883473  , 0.17406907],
       [0.59743684, 0.30510725, 0.61243659, 0.20535053],
       [0.25246338, 0.6456283 , 0.25161632, 0.69279808],
       [0.99271113, 0.37451587, 0.19199661, 0.58909654]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [32]:
vector1 = np.random.randint(1, 11, size=(5, ), dtype=np.int8)
vector2 = np.random.randint(1, 11, size=(5, ), dtype=np.int8)

print(f"{vector1 = }")
print(f"{vector2 = }")

operation_add = vector1 + vector2
print(f"{operation_add = }")

operation_sup = vector1 - vector2
print(f"{operation_sup = }")

operation_multi = vector1 * vector2
print(f"{operation_multi = }")


vector1 = array([1, 8, 3, 3, 9], dtype=int8)
vector2 = array([ 6, 10,  2,  1,  2], dtype=int8)
operation_add = array([ 7, 18,  5,  4, 11], dtype=int8)
operation_sup = array([-5, -2,  1,  2,  7], dtype=int8)
operation_multi = array([ 6, 80,  6,  3, 18], dtype=int8)


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [33]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

print(f"{vector1 = }")
print(f"{vector2 = }")

dot_product = vector1 @ vector2
print(f"{dot_product = }")

vector1 = array([0.57537407, 0.13962333, 0.77672308, 0.28376276, 0.0124065 ,
       0.10044351, 0.39482436])
vector2 = array([0.32700646, 0.21544932, 0.14417129, 0.31110322, 0.58323034,
       0.74686978, 0.24483985])
dot_product = 0.5974162790332684


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [34]:
matrix_22 = np.random.randint(1, 11, size=(2, 2))
matrix_23 = np.random.randint(1, 11, size=(2, 3))
matrix_dotproduct = np.dot(matrix_22, matrix_23)
matrix_dotproduct

array([[85, 81, 98],
       [47, 35, 54]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [35]:
matrix_33 = np.random.randint(1, 11, size=(3, 3), dtype=int)
inverse_matrix_33 = np.linalg.inv(matrix_33)
matrix_33, inverse_matrix_33

(array([[4, 8, 4],
        [8, 3, 5],
        [1, 7, 1]]),
 array([[-5.33333333e-01,  3.33333333e-01,  4.66666667e-01],
        [-5.00000000e-02,  4.18952085e-18,  2.00000000e-01],
        [ 8.83333333e-01, -3.33333333e-01, -8.66666667e-01]]))

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [36]:
matrix_44 = np.random.rand(4, 4)
inverse_matrix_44 = matrix_44.T
matrix_44, inverse_matrix_44

(array([[0.13620111, 0.68615631, 0.97693361, 0.1016467 ],
        [0.46978675, 0.73107885, 0.87315146, 0.38299833],
        [0.56002027, 0.53772934, 0.63739187, 0.95840466],
        [0.66995836, 0.07886261, 0.47052837, 0.86871512]]),
 array([[0.13620111, 0.46978675, 0.56002027, 0.66995836],
        [0.68615631, 0.73107885, 0.53772934, 0.07886261],
        [0.97693361, 0.87315146, 0.63739187, 0.47052837],
        [0.1016467 , 0.38299833, 0.95840466, 0.86871512]]))

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [37]:
matrix_34 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
vector_matrix_dot = matrix_34 @ vector_4
matrix_34, vector_4, vector_matrix_dot

(array([[9, 7, 9, 8],
        [5, 7, 7, 2],
        [9, 2, 7, 1]]),
 array([5, 8, 6, 3]),
 array([179, 129, 106]))

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [38]:
matrix_23 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
vector_matrix_dot = matrix_23 @ vector_3
matrix_23, vector_3, vector_matrix_dot

(array([[0.35459589, 0.46479588, 0.56397795],
        [0.94903376, 0.12965321, 0.52785559]]),
 array([0.51208762, 0.03518375, 0.17600946]),
 array([0.29720288, 0.58345771]))

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [39]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
multiply = m1 * m2
m1, m2, multiply

(array([[10,  4],
        [ 9,  1]]),
 array([[10,  6],
        [ 6,  5]]),
 array([[100,  24],
        [ 54,   5]]))

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [40]:
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 2))
dotproduct = m1 @ m2
m1, m2, dotproduct

(array([[ 5,  7],
        [10,  6]]),
 array([[4, 5],
        [9, 5]]),
 array([[83, 60],
        [94, 80]]))

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.


In [41]:
matrix_55 = np.random.randint(1, 101, size=(5, 5))
sum_matrix_55 = matrix_55.sum()
matrix_55, sum_matrix_55

(array([[11, 74, 81, 41, 42],
        [44, 15, 55, 56, 92],
        [66, 64, 48,  8, 22],
        [58, 29, 41, 41, 52],
        [44, 14, 51,  1, 44]]),
 1094)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.


In [42]:
m1 = np.random.randint(1, 11, size=(4, 4))
m2 = np.random.randint(1, 11, size=(4, 4))
sub_m = m1 - m2
m1, m2, sub_m

(array([[9, 3, 9, 5],
        [4, 9, 3, 7],
        [6, 8, 3, 8],
        [3, 8, 7, 4]]),
 array([[ 3,  3,  5, 10],
        [ 6,  6,  8,  1],
        [ 8,  4,  6,  4],
        [ 1,  1,  7,  7]]),
 array([[ 6,  0,  4, -5],
        [-2,  3, -5,  6],
        [-2,  4, -3,  4],
        [ 2,  7,  0, -3]]))

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [43]:
matrix_33 = np.random.rand(3, 3)
row_sum = matrix_33.sum(axis=1).reshape(-1, 1)
matrix_33, row_sum


(array([[0.40419475, 0.91207428, 0.34565152],
        [0.33322115, 0.02939006, 0.03444534],
        [0.74690605, 0.42294125, 0.92649685]]),
 array([[1.66192055],
        [0.39705655],
        [2.09634415]]))

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [44]:
matrix_34 = np.random.randint(1, 100, size=(3, 4))
squared_matrix = np.square(matrix_34)
matrix_34, squared_matrix


(array([[72,  6,  5, 68],
        [ 4, 78, 75,  4],
        [10, 20, 21, 97]]),
 array([[5184,   36,   25, 4624],
        [  16, 6084, 5625,   16],
        [ 100,  400,  441, 9409]]))

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.


In [45]:
vector_5 = np.random.randint(1, 51, size=4)
squared_vector = np.square(vector_5)
vector_5, squared_vector

(array([21, 45, 16, 11]), array([ 441, 2025,  256,  121]))